language: java
jdk: openjdk11
notifications:
  email: false
before_install: true
install: mvn --batch-mode $MAVEN_OPTIONS dependency:go-offline compile test-compile 
before_script: true
script: mvn --batch-mode $MAVEN_OPTIONS install
